/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import javax.swing.JButton;
import javax.swing.Icon;
import javax.swing.JOptionPane;




/**
 *
 * @author csolti
 */
public class Jatek extends javax.swing.JFrame {

    /**
     * Creates new form Jatek
     */
    public Jatek() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jlblLeiras = new javax.swing.JLabel();
        jbttn1_ = new javax.swing.JButton();
        jbttn1_2 = new javax.swing.JButton();
        jbttn1_3 = new javax.swing.JButton();
        jbttn1_4 = new javax.swing.JButton();
        jbttn2_ = new javax.swing.JButton();
        jbttn2_2 = new javax.swing.JButton();
        jbttn2_3 = new javax.swing.JButton();
        jbttn2_4 = new javax.swing.JButton();
        jbttn3_2 = new javax.swing.JButton();
        jbttn3_3 = new javax.swing.JButton();
        jbttn4_ = new javax.swing.JButton();
        jbttn3_4 = new javax.swing.JButton();
        jbttn3_ = new javax.swing.JButton();
        jbttn4_2 = new javax.swing.JButton();
        jbttn4_3 = new javax.swing.JButton();
        jbttn4_4 = new javax.swing.JButton();
        jlblValasztas = new javax.swing.JLabel();
        jlblLepesszam = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Logikai játék");
        setResizable(false);

        jlblLeiras.setText("Válaszd ki az egyik oszlop legfelső elemét!");

        jbttn1_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttn1_ActionPerformed(evt);
            }
        });

        jbttn1_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/kek.png"))); // NOI18N
        jbttn1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttn1_2ActionPerformed(evt);
            }
        });

        jbttn1_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/piros.png"))); // NOI18N
        jbttn1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttn1_3ActionPerformed(evt);
            }
        });

        jbttn1_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/zold.png"))); // NOI18N
        jbttn1_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttn1_4ActionPerformed(evt);
            }
        });

        jbttn2_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttn2_ActionPerformed(evt);
            }
        });

        jbttn2_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/zold.png"))); // NOI18N
        jbttn2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttn2_2ActionPerformed(evt);
            }
        });

        jbttn2_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/piros.png"))); // NOI18N
        jbttn2_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttn2_3ActionPerformed(evt);
            }
        });

        jbttn2_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/zold.png"))); // NOI18N
        jbttn2_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttn2_4ActionPerformed(evt);
            }
        });

        jbttn3_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/piros.png"))); // NOI18N
        jbttn3_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttn3_2ActionPerformed(evt);
            }
        });

        jbttn3_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/kek.png"))); // NOI18N
        jbttn3_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttn3_3ActionPerformed(evt);
            }
        });

        jbttn4_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttn4_ActionPerformed(evt);
            }
        });

        jbttn3_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/kek.png"))); // NOI18N
        jbttn3_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttn3_4ActionPerformed(evt);
            }
        });

        jbttn3_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttn3_ActionPerformed(evt);
            }
        });

        jbttn4_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttn4_2ActionPerformed(evt);
            }
        });

        jbttn4_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttn4_3ActionPerformed(evt);
            }
        });

        jbttn4_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttn4_4ActionPerformed(evt);
            }
        });

        jlblValasztas.setText("Kiválasztva: -");

        jlblLepesszam.setText("Lépések száma: 0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbttn1_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbttn1_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbttn1_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbttn1_, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbttn2_, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jbttn2_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbttn2_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbttn2_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbttn3_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbttn3_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbttn3_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbttn3_, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbttn4_, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbttn4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbttn4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbttn4_4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jlblLeiras)
                    .addComponent(jlblValasztas)
                    .addComponent(jlblLepesszam))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbttn1_, jbttn1_2, jbttn1_3, jbttn1_4, jbttn2_, jbttn2_2, jbttn2_3, jbttn2_4, jbttn3_, jbttn3_2, jbttn3_3, jbttn3_4, jbttn4_, jbttn4_2, jbttn4_3, jbttn4_4});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblLeiras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbttn1_, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbttn1_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbttn1_3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbttn1_4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbttn4_, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbttn4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbttn4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbttn4_4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbttn2_, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbttn3_, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbttn3_2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbttn3_3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbttn3_4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbttn2_2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbttn2_3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbttn2_4)))))
                .addGap(18, 18, 18)
                .addComponent(jlblValasztas)
                .addGap(18, 18, 18)
                .addComponent(jlblLepesszam)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbttn1_, jbttn1_2, jbttn1_3, jbttn1_4, jbttn2_, jbttn2_2, jbttn2_3, jbttn2_4, jbttn3_, jbttn3_2, jbttn3_3, jbttn3_4, jbttn4_, jbttn4_2, jbttn4_3, jbttn4_4});

        jTabbedPane1.addTab("Játék", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Megoldás", jPanel2);

        jMenu1.setText("Program");

        jMenuItem4.setText("Új játék");
        jMenu1.add(jMenuItem4);
        jMenu1.add(jSeparator2);

        jMenuItem1.setText("Mentés");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Betöltés");
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem3.setText("Kilépés");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    JButton aktivGomb = null;
    JButton elozoGomb = null;
    String aktiv = "";
    int klikk = 0;
    private void jbttn1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttn1_2ActionPerformed
        aktivGomb = jbttn1_2;
        gombKezelo(aktivGomb);
    }//GEN-LAST:event_jbttn1_2ActionPerformed

    private void jbttn2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttn2_2ActionPerformed
        aktivGomb = jbttn2_2;
        gombKezelo(aktivGomb);
    }//GEN-LAST:event_jbttn2_2ActionPerformed

    private void jbttn3_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttn3_2ActionPerformed
        aktivGomb = jbttn3_2;
        gombKezelo(aktivGomb);
    }//GEN-LAST:event_jbttn3_2ActionPerformed

    private void jbttn4_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttn4_4ActionPerformed
        aktivGomb = jbttn4_4;
        gombKezelo(aktivGomb);
    }//GEN-LAST:event_jbttn4_4ActionPerformed

    private void jbttn1_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttn1_ActionPerformed
        figyelmeztetes();
    }//GEN-LAST:event_jbttn1_ActionPerformed

    private void jbttn2_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttn2_ActionPerformed
        figyelmeztetes();
    }//GEN-LAST:event_jbttn2_ActionPerformed

    private void jbttn3_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttn3_ActionPerformed
        figyelmeztetes();
    }//GEN-LAST:event_jbttn3_ActionPerformed

    private void jbttn4_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttn4_ActionPerformed
        figyelmeztetes();
    }//GEN-LAST:event_jbttn4_ActionPerformed

    private void jbttn4_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttn4_2ActionPerformed
        aktivGomb = jbttn4_2;
        gombKezelo(aktivGomb);
    }//GEN-LAST:event_jbttn4_2ActionPerformed

    private void jbttn1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttn1_3ActionPerformed
        aktivGomb = jbttn1_3;
        gombKezelo(aktivGomb);
    }//GEN-LAST:event_jbttn1_3ActionPerformed

    private void jbttn2_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttn2_3ActionPerformed
        aktivGomb = jbttn2_3;
        gombKezelo(aktivGomb);
    }//GEN-LAST:event_jbttn2_3ActionPerformed

    private void jbttn3_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttn3_3ActionPerformed
        aktivGomb = jbttn3_3;
        gombKezelo(aktivGomb);
    }//GEN-LAST:event_jbttn3_3ActionPerformed

    private void jbttn4_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttn4_3ActionPerformed
        aktivGomb = jbttn4_3;
        gombKezelo(aktivGomb);
    }//GEN-LAST:event_jbttn4_3ActionPerformed

    private void jbttn1_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttn1_4ActionPerformed
        aktivGomb = jbttn1_4;
        gombKezelo(aktivGomb);
    }//GEN-LAST:event_jbttn1_4ActionPerformed

    private void jbttn2_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttn2_4ActionPerformed
        aktivGomb = jbttn2_4;
        gombKezelo(aktivGomb);
    }//GEN-LAST:event_jbttn2_4ActionPerformed

    private void jbttn3_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttn3_4ActionPerformed
        aktivGomb = jbttn3_4;
        gombKezelo(aktivGomb);
    }//GEN-LAST:event_jbttn3_4ActionPerformed
    
    void figyelmeztetes(){
        JOptionPane.showMessageDialog(rootPane, "Ezen a szinten nem használható");
    }
    
    private void gombKezelo(JButton gomb){
        Icon ikon = gomb.getIcon();
        if(ikon != null){
            /* ... "/kepek/kek.jpg" */
            String szoveg = ikon.toString();
            String elsoBetu = szoveg.substring(szoveg.lastIndexOf('/') + 1, szoveg.lastIndexOf('/') + 2);
            aktiv = elsoBetu+"";
            jlblLeiras.setText("Jelöld, hogy hova rakod!");
            String sz = "";
            //if(elsoBetu == 'k')
            if (aktiv.equals('k')){
                sz = "kék";
            }else if (aktiv.equals('p')){
                sz = "piros";
            }else if (aktiv.equals('z')){
                sz = "zöld";
            }
            elozoGomb = gomb;
            jlblValasztas.setText("Kiválsztva: ");
            klikk++;//klikk = klikk + 1
            jlblLepesszam.setText("Lépések száma: " + klikk);
        }else{
                if(aktiv.equals("k")){
                gomb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/kek.png")));

            }else if(aktiv.equals("z")){
                gomb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/zold.png")));

            }else if(aktiv.equals("p")){
                gomb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/piros.png")));

            }
            aktiv = "";
            elozoGomb.setIcon(null);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jatek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jatek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jatek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jatek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jatek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbttn1_;
    private javax.swing.JButton jbttn1_2;
    private javax.swing.JButton jbttn1_3;
    private javax.swing.JButton jbttn1_4;
    private javax.swing.JButton jbttn2_;
    private javax.swing.JButton jbttn2_2;
    private javax.swing.JButton jbttn2_3;
    private javax.swing.JButton jbttn2_4;
    private javax.swing.JButton jbttn3_;
    private javax.swing.JButton jbttn3_2;
    private javax.swing.JButton jbttn3_3;
    private javax.swing.JButton jbttn3_4;
    private javax.swing.JButton jbttn4_;
    private javax.swing.JButton jbttn4_2;
    private javax.swing.JButton jbttn4_3;
    private javax.swing.JButton jbttn4_4;
    private javax.swing.JLabel jlblLeiras;
    private javax.swing.JLabel jlblLepesszam;
    private javax.swing.JLabel jlblValasztas;
    // End of variables declaration//GEN-END:variables
}
